import { useState, useRef, useEffect } from 'react';
import { motion } from 'motion/react';
import { Play, Square, Sliders, Activity, Disc, Zap, Info, Shield, HelpCircle, Waves, Scissors, Maximize2, Coffee, Cloud, RefreshCw, Volume2 } from 'lucide-react';
import { FAQ } from '../components/UI/FAQ';
import { ProceduralEngine } from '../lib/proceduralEngine';

const engine = new ProceduralEngine();

export const ProceduralGenerator = () => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isInitialized, setIsInitialized] = useState(false);
  const [tempo, setTempo] = useState(90);
  const [volume, setVolume] = useState(0.5);
  const [vibe, setVibe] = useState('Lo-Fi Chill');
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const initEngine = async () => {
    await engine.init();
    setIsInitialized(true);
  };

  const togglePlay = () => {
    if (isPlaying) {
      engine.stop();
    } else {
      engine.start();
    }
    setIsPlaying(!isPlaying);
  };

  useEffect(() => {
    if (!isInitialized) return;
    
    const analyser = engine.getAnalyser();
    if (!analyser || !canvasRef.current) return;

    const ctx = canvasRef.current.getContext('2d');
    if (!ctx) return;

    const dataArray = new Uint8Array(analyser.frequencyBinCount);
    let animationId: number;

    const draw = () => {
      analyser.getByteTimeDomainData(dataArray);
      ctx.fillStyle = '#0a0a0b';
      ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
      
      // Grid
      ctx.strokeStyle = '#1e1e20';
      ctx.lineWidth = 0.5;
      for(let i=0; i<ctx.canvas.width; i+=40) {
        ctx.beginPath(); ctx.moveTo(i, 0); ctx.lineTo(i, ctx.canvas.height); ctx.stroke();
      }
      for(let i=0; i<ctx.canvas.height; i+=40) {
        ctx.beginPath(); ctx.moveTo(0, i); ctx.lineTo(ctx.canvas.width, i); ctx.stroke();
      }

      ctx.lineWidth = 2;
      ctx.strokeStyle = '#a855f7';
      ctx.beginPath();

      const sliceWidth = ctx.canvas.width * 1.0 / analyser.frequencyBinCount;
      let x = 0;

      for (let i = 0; i < analyser.frequencyBinCount; i++) {
        const v = dataArray[i] / 128.0;
        const y = v * ctx.canvas.height / 2;

        if (i === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);

        x += sliceWidth;
      }

      ctx.stroke();
      animationId = requestAnimationFrame(draw);
    };

    draw();
    return () => cancelAnimationFrame(animationId);
  }, [isInitialized]);

  useEffect(() => {
    engine.setTempo(tempo);
  }, [tempo]);

  useEffect(() => {
    engine.setVolume(volume);
  }, [volume]);

  const vibes = [
    { title: 'Lo-Fi Chill', desc: 'Slow, dusty, nostalgic', color: 'text-blue-400' },
    { title: 'Dark Techno', desc: 'Industrial, driving, dark', color: 'text-purple-400' },
    { title: 'Ethereal Ambient', desc: 'Drifting, flowing, calm', color: 'text-accent-pink' }
  ];

  const faqs = [
    {
      question: "Is the music truly royalty-free?",
      answer: "Yes. Every loop generated by ToneForge is procedurally synthesized in your browser. Since there is no human composer and the code is running locally for you, the resulting audio is free for use in your YouTube videos, streams, and podcasts without risk of copyright strikes."
    },
    {
      question: "How does procedural generation work?",
      answer: "We use mathematical algorithms to define melody, rhythm, and harmonic structure. Our engine uses Web Audio oscillators and sampling techniques to build unique patterns on the fly based on the 'vibe' you select."
    },
    {
      question: "Can I download the generated loops?",
      answer: "Absolutely. Once the audio engine is running and you 'Generate New Loop', you can use the recording feature (Beta) to save high-quality WAV files directly to your device."
    }
  ];

  return (
    <div className="max-w-4xl mx-auto pt-6 px-6 pb-16 animate-reveal">
      <div className="flex justify-between items-center mb-8">
        <div className="flex items-center gap-4">
          <div className="flex flex-col">
            <h1 className="text-4xl font-bold tracking-tighter italic">ToneForge <span className="neon-text text-white">X</span></h1>
            <p className="text-[10px] uppercase tracking-[0.3em] font-bold opacity-30">Neural Music Synthesis Engine</p>
          </div>
        </div>
        <button className="px-4 py-2 bg-white/5 border border-white/10 rounded-full flex items-center gap-2 text-[9px] font-bold tracking-widest hover:bg-white/10 transition-all text-muted hover:text-white group">
          <Info className="w-3.5 h-3.5 group-hover:text-accent transition-colors" />
          WHY NO YOUTUBE?
        </button>
      </div>

      <div className="space-y-4">
        {/* Visualizer Panel */}
        <section className="glass-panel p-6 bg-[#0a0a0b] border-[#1e1e20] relative overflow-hidden h-40">
          <div className="absolute top-4 left-4 text-[9px] font-mono opacity-30 text-accent uppercase tracking-widest z-10 flex items-center gap-2">
            <div className="w-1.5 h-1.5 rounded-full bg-accent animate-pulse" />
            MAIN_OUT_L // R
          </div>
          {!isInitialized ? (
            <div className="w-full h-full flex items-center justify-center">
              <button 
                onClick={initEngine}
                className="group flex flex-col items-center gap-3"
              >
                <div className="w-12 h-12 rounded-full bg-accent/10 border border-accent/30 flex items-center justify-center group-hover:scale-105 transition-all shadow-[0_0_20px_rgba(168,85,247,0.1)]">
                  <Zap className="w-5 h-5 text-accent" />
                </div>
                <span className="text-[8px] font-bold uppercase tracking-[0.2em] opacity-40">Initialize Core</span>
              </button>
            </div>
          ) : (
            <canvas ref={canvasRef} width={800} height={160} className="w-full h-full grayscale-[0.3]" />
          )}
        </section>

        {/* Control Panel */}
        <section className="glass-panel p-8 bg-[#0a0a0b] border-[#1e1e20] flex items-center gap-10 relative overflow-hidden">
          <button 
            disabled={!isInitialized}
            onClick={togglePlay}
            className={`w-14 h-14 rounded-full flex items-center justify-center transition-all ${isPlaying ? 'bg-accent shadow-[0_0_30px_rgba(168,85,247,0.4)]' : 'bg-white/5 border border-white/10 hover:bg-white/10'} ${!isInitialized && 'opacity-20 pointer-events-none'}`}
          >
            {isPlaying ? <Square className="w-5 h-5 text-white" /> : <Play className="w-5 h-5 text-white ml-1" />}
          </button>

          <div className="flex-1 space-y-2">
            <div className="flex justify-between items-end">
              <div>
                <p className="text-[9px] uppercase tracking-widest opacity-20 font-bold mb-0.5">Status</p>
                <p className={`text-lg font-black tracking-tighter ${isPlaying ? 'text-accent' : 'text-muted'}`}>
                  {isPlaying ? 'PLAYING' : 'STANDBY'}
                </p>
              </div>
              <div className="text-right">
                <p className="text-[9px] uppercase tracking-widest opacity-20 font-bold mb-0.5">Tempo</p>
                <p className="text-xs font-bold font-mono tracking-widest">{tempo} BPM</p>
              </div>
            </div>
            <input 
              type="range"
              min="60"
              max="180"
              value={tempo}
              onChange={(e) => setTempo(parseInt(e.target.value))}
              className="w-full h-1 bg-white/5 rounded-full appearance-none accent-accent cursor-pointer"
            />
          </div>

          <div className="w-px h-12 bg-white/5 mx-2" />

          <div className="flex flex-col items-center gap-2">
             <p className="text-[8px] uppercase tracking-widest opacity-20 font-bold">Master</p>
             <div className="h-16 w-1 bg-white/5 rounded-full relative">
               <motion.div 
                 className="absolute bottom-0 left-0 right-0 bg-accent rounded-full shadow-[0_0_10px_rgba(168,85,247,0.5)]"
                 style={{ height: `${volume * 100}%` }}
               />
               <input 
                 type="range" 
                 min="0" 
                 max="1" 
                 step="0.01"
                 value={volume}
                 onChange={(e) => setVolume(parseFloat(e.target.value))}
                 className="absolute inset-0 w-full h-full opacity-0 cursor-pointer" 
                 style={{ appearance: 'slider-vertical' } as any}
               />
             </div>
          </div>
        </section>

        {/* Global FX & Vibes */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <section className="glass-panel p-6 bg-[#0a0a0b] border-[#1e1e20]">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-2">
                <Activity className="w-4 h-4 text-accent-pink" />
                <h3 className="text-xs font-bold uppercase tracking-widest">Remix FX Chain</h3>
              </div>
              <span className="px-2 py-0.5 border border-accent-pink/30 text-accent-pink text-[7px] font-bold rounded uppercase tracking-tighter">Live Processing</span>
            </div>

            <div className="w-full aspect-[21/9] bg-black rounded-lg border border-white/5 relative overflow-hidden mb-6 group">
              <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(circle, rgba(255,255,255,1) 1px, transparent 1px)', backgroundSize: '20px 20px' }} />
              <div className="absolute top-3 left-3 text-[8px] uppercase tracking-widest opacity-20 font-bold">Filter (X)</div>
              <div className="absolute top-3 right-3 text-[8px] uppercase tracking-widest opacity-20 font-bold">Crush (Y)</div>
              <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                <motion.div 
                  className="w-4 h-4 rounded-full bg-accent-pink shadow-[0_0_20px_rgba(236,72,153,0.8)] pointer-events-auto cursor-grab active:cursor-grabbing"
                  drag
                  dragConstraints={{ left: -80, right: 80, top: -40, bottom: 40 }}
                  whileTap={{ scale: 0.8 }}
                  onDrag={(e, info) => {
                    engine.setFilter(1000 + info.point.x * 5);
                  }}
                />
              </div>
              <div className="absolute bottom-2 w-full text-center text-[7px] uppercase tracking-widest opacity-15">Drag to morph sound</div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              {[
                { name: 'Space Verb', icon: Waves },
                { name: 'Chopped', icon: Scissors },
                { name: 'Widen', icon: Maximize2 },
                { name: 'Tape Stop', icon: Square }
              ].map((fx, i) => (
                <button 
                  key={fx.name} 
                  className={`py-3 px-4 bg-white/5 border border-border rounded-lg flex items-center justify-center gap-2 transition-all hover:bg-white/10 group ${i === 0 ? 'border-accent-pink/50 bg-accent-pink/5 text-accent-pink' : 'text-muted'}`}
                >
                  <fx.icon className={`w-3.5 h-3.5 ${i === 0 ? 'opacity-100' : 'opacity-40 group-hover:opacity-100'}`} />
                  <p className="text-[9px] font-bold uppercase tracking-widest">{fx.name}</p>
                </button>
              ))}
            </div>
          </section>

          <section className="glass-panel p-6 bg-[#0a0a0b] border-[#1e1e20]">
            <div className="flex items-center gap-2 mb-6">
              <Disc className="w-3 h-3 text-accent" />
              <h3 className="text-xs font-bold uppercase tracking-widest">Synthesis Engine</h3>
            </div>
            
            <div className="flex flex-col gap-3 mb-6">
              {[
                { title: 'Lo-Fi Chill', desc: 'Slow, dusty, nostalgic', icon: Coffee },
                { title: 'Dark Techno', desc: 'Industrial, driving, dark', icon: Zap },
                { title: 'Ethereal Ambient', desc: 'Drifting, flowing, calm', icon: Cloud }
              ].map((v) => (
                <button 
                  key={v.title}
                  onClick={() => setVibe(v.title)}
                  className={`p-3 border rounded-xl text-left transition-all flex items-center gap-4 group ${vibe === v.title ? 'border-accent bg-accent/5 ring-1 ring-accent/20 shadow-[inset_0_0_20px_rgba(168,85,247,0.05)]' : 'border-white/5 hover:border-white/10 bg-white/2'}`}
                >
                  <div className={`w-10 h-10 rounded-lg flex items-center justify-center transition-all ${vibe === v.title ? 'bg-accent text-white shadow-lg shadow-accent/20' : 'bg-white/5 text-muted group-hover:text-white'}`}>
                    <v.icon className="w-4 h-4" />
                  </div>
                  <div>
                    <p className={`text-[10px] font-bold ${vibe === v.title ? 'text-white' : 'text-white/60'}`}>{v.title}</p>
                    <p className="text-[8px] opacity-40 uppercase tracking-tight mt-0.5">{v.desc}</p>
                  </div>
                </button>
              ))}
            </div>

            <button 
              onClick={() => {
                engine.regenerate();
                // Simple visual feedback
                setTempo(t => t + (Math.random() > 0.5 ? 1 : -1));
              }}
              className="w-full py-4 rounded-xl bg-gradient-to-r from-accent to-accent-pink text-white text-[10px] font-bold uppercase tracking-[0.2em] shadow-[0_0_30px_rgba(168,85,247,0.3)] hover:shadow-[0_0_40px_rgba(168,85,247,0.5)] hover:scale-[1.01] active:scale-95 transition-all flex items-center justify-center gap-2"
            >
              <RefreshCw className="w-4 h-4 animate-spin-slow" />
              Regenerate Pattern
            </button>
          </section>
        </div>
      </div>

      {/* SEO Content Section */}
      <section className="mt-12 glass-panel p-8 text-left border-[#1e1e20]">
        <h2 className="text-xl font-bold tracking-tight mb-4">Why Procedural Music?</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-[11px] text-muted leading-relaxed">
          <p>
            Standard stock music platforms provide fixed files. When thousands of creators use the same file, YouTube's <span className="text-white font-medium">Content ID</span> systems easily identify and claim the audio. ToneForge changes the game by synthesizing audio in real-time using your browser's computational power.
          </p>
          <p>
            Our procedural engine ensures that rhythmic structures and harmonic distributions are uniquely generated for every session. By utilizing <span className="text-white font-medium">WASM-powered STFT algorithms</span>, we create an acoustic fingerprint that is mathematically distinct from any existing library song, giving you total creative sovereignty.
          </p>
        </div>
      </section>

      <div className="mt-12 text-left">
        <FAQ items={faqs} />
      </div>
    </div>
  );
};
